### ISSUE TITLE
Overriding `_stop` in `Thread` subclass causes bug in new Python versions

### ISSUE THREAD

**Issue by user202729** [tschulte/plover_auto_reconnect_machine#1]
According to [the documentation](https://docs.python.org/3/library/threading.html#thread-objects)

> No other methods (except for the constructor) should be overridden in a subclass. In other words, only override the `__init__()` and `run()` methods of this class.

[The `AutoReconnectMachine` class uses the `_stop` member](https://github.com/tschulte/plover_auto_reconnect_machine/blob/master/plover_auto_reconnect_machine.py#L13), and it causes problems with the newer versions of Python (which also uses `_stop` for its own purposes)

(however the bug doesn't really affect anything, I only encounter it while developing something else unrelated)

**Comment by tschulte** [comment]
Oh, I guess I did not want to override _stop, but define it. But I'm not sure anymore. Is the solution to just rename _stop?

**Comment by user202729** [comment]
For now, renaming it to something else (`__stop` for example) will do it, but it still violates Python's documentation and might be problematic in some future versions.

The proper solution should be to not inherit from `Thread`, but make the thread a member of the class instead.

**Comment by tschulte** [comment]
Currently I don't use this plugin, because my setup does not need it. @user202729, can you check, if https://github.com/tschulte/plover_auto_reconnect_machine/pull/2 fixes this issue and still works?
